In [49]:
import numpy as np
import pickle as p

In [47]:
np.concatenate([[1,2],[3,4]])

array([1, 2, 3, 4])

In [48]:
array1 = np.arange(3)
array2 = np.linspace(10,12,3)

In [65]:
array = np.random.randint(15, size=(3,5))
array

array([[ 5, 11,  4,  2,  9],
       [ 2,  9,  9,  8, 12],
       [ 0, 10,  5,  0, 13]])

In [78]:
if (3<4) is True or (5<2) is True:
    print('Correct')

Correct


In [88]:
array = np.arange(15).reshape(3,5)
array

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [111]:
ax = ['ax{}'.format(i) for i in range(4)]
ax

['ax0', 'ax1', 'ax2', 'ax3']

In [122]:
import cv2
color_t = getattr(cv2, 'COLOR_RGB2GRAY')

error: /Users/jenkins/miniconda/1/x64/conda-bld/conda_1486587097465/work/opencv-3.1.0/modules/imgproc/src/color.cpp:7935: error: (-215) depth == CV_8U || depth == CV_16U || depth == CV_32F in function cvtColor


In [61]:
p.dump((array1,array2), open('./sample.p', 'wb'))

In [62]:
p.load(open('./sample.p', 'rb'))

(array([0, 1, 2]), array([ 10.,  11.,  12.]))

In [64]:
def testfunc(a, b=2):
    return a*b
testfun(2, 7)

14

In [14]:
array3 = np.concatenate([array1, array2])
array3

array([  0.,   1.,   2.,  10.,  11.,  12.])

In [16]:
array3[:3], array3[3:]

(array([ 0.,  1.,  2.]), array([ 10.,  11.,  12.]))

In [17]:
np.vstack([array1, array2])

array([[  0.,   1.,   2.],
       [ 10.,  11.,  12.]])

In [19]:
array4 = np.array([]).reshape(0,6)
array4

array([], shape=(0, 6), dtype=float64)

In [26]:
if not array4:
    print('Found it')

Found it


In [30]:
np.vstack([array4, [1,2,3,4,5,6]])

array([[ 1.,  2.,  3.,  4.,  5.,  6.]])

In [32]:
test_array = np.random.randint(100, size=(3,6))
test_array

array([[60, 13, 51, 93, 82, 51],
       [86, 66, 65, 65, 27, 47],
       [81, 23, 93, 88,  0,  9]])

In [43]:
a, b = np.split(np.mean(test_array, axis=0), 2)
a, b

(array([ 75.66666667,  34.        ,  69.66666667]),
 array([ 82.        ,  36.33333333,  35.66666667]))

In [45]:
np.zeros(6).reshape(1,6)

array([[ 0.,  0.,  0.,  0.,  0.,  0.]])